### ISSUE TITLE
User agent

### ISSUE THREAD

**Issue by calvinti12** [salarcode/ASProxy#1]
Hello will there be any fix for a user agent at this time is not working

**Comment by salarcode** [comment]
Hi can you be more specific with the details?
Also this app is out of support.

**Comment by calvinti12** [comment]
Oh OK sorry. I just like using it but it seems every time I put the custom user agent in it does not switch It will be nice to see a fix even if I have to pay

**Comment by salarcode** [comment]
Sorry but i'm not looking into the issues of this app anymore.
